# If you add a page, you must add it to the index here
pages:
  - Home: 'index.md'
  - Style Guide: 'styleguide.md'
  - Getting Started:
    - Home: 'gettingstarted/index.md'
    - Structuring Your Mod: 'gettingstarted/structuring.md'
    - Forge Update Checker: 'gettingstarted/autoupdate.md'
  - Concepts:
    - Sides: 'concepts/sides.md'
    - Resources: 'concepts/resources.md'
    - Registries: 'concepts/registries.md'
    - The Fingerprint Violation Event: 'concepts/jarsigning.md'
  - Blocks:
    - Home: 'blocks/blocks.md'
    - Interaction: 'blocks/interaction.md'
  - Blockstates:
    - Intro to Blockstates: 'blockstates/states.md' 
    - Intro to Blockstate JSONs: 'blockstates/introduction.md'
    - Forge Blockstate JSON: 'blockstates/forgeBlockstates.md'
  - Tile Entities:
    - Special Renderer: 'tileentities/tesr.md'
  - Items:
    - Home: 'items/items.md'
    - Loot Tables: 'items/loot_tables.md'
  - Events:
    - Basic Usage: 'events/intro.md'
  - Networking:
    - Home: 'networking/index.md'
    - Overview: 'networking/overview.md'
    - SimpleImpl: 'networking/simpleimpl.md'
  - Data Storage:
    - Capabilities: 'datastorage/capabilities.md'
    - World Saved Data: 'datastorage/worldsaveddata.md'
    - Extended Entity Properties: 'datastorage/extendedentityproperties.md'
  - Utilities:
    - OreDictionary: 'utilities/oredictionary.md'
  - Effects:
    - Sounds: 'effects/sounds.md'
  - Conventions:
    - Versioning: 'conventions/versioning.md'
    - Locations: 'conventions/locations.md'
    - Loading Stages: 'conventions/loadstages.md'
  - Contributing to Forge:
    - Getting Started: 'forgedev/index.md'
    - PR Guidlines: 'forgedev/prguidelines.md'

# Do not edit in PRs below here
site_name: Forge Documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - toc:
      permalink: ' '

theme: null
theme_dir: 'forge_theme'
