# If you add a page, you must add it to the index here
nav:
  - Home: 'index.md'
  - Contributing to the Docs: 'contributing.md'
  - Getting Started:
    - Introduction: 'gettingstarted/index.md'
    - Structuring Your Mod: 'gettingstarted/structuring.md'
    - Versioning: 'gettingstarted/versioning.md'
  - Core Concepts:
    - Registries: 'concepts/registries.md'
    - Sides: 'concepts/sides.md'
    - Events: 'concepts/events.md'
    - Mod Lifecycle: 'concepts/lifecycle.md'
    - Resources: 'concepts/resources.md'
    - Internationalization: 'concepts/internationalization.md'
  - Blocks:
    - Introduction: 'blocks/index.md'
    - Block States: 'blocks/states.md'
  - Items:
    - Introduction: 'items/index.md'
    - BlockEntityWithoutLevelRenderer: 'items/bewlr.md'
  - Networking:
    - Introduction: 'networking/index.md'
    - SimpleImpl: 'networking/simpleimpl.md'
    - Synchronizing Entities: 'networking/entities.md'
  - Block Entities:
    - Introduction: 'blockentities/index.md'
    - BlockEntityRenderer: 'blockentities/ber.md'
  - Game Effects:
    - Particles: 'gameeffects/particles.md'
    - Sounds: 'gameeffects/sounds.md'
  - Data Storage:
    - Capabilities: 'datastorage/capabilities.md'
    - Saved Data: 'datastorage/saveddata.md'
  - Rendering:
    - Model Loaders:
      - Introduction: 'rendering/modelloaders/index.md'
      - Baked Model: 'rendering/modelloaders/bakedmodel.md'
      - Perspective: 'rendering/modelloaders/perspective.md'
      - Item Overrides: 'rendering/modelloaders/itemoverrides.md'
  - Resources:
    - Client Assets:
      - Introduction: 'resources/client/index.md'
      - Models:
        - Introduction: 'resources/client/models/index.md'
        - Texture Tinting: 'resources/client/models/tinting.md'
        - Item Properties: 'resources/client/models/itemproperties.md'
    - Server Data:
      - Introduction: 'resources/server/index.md'
      - Recipes:
        - Introduction: 'resources/server/recipes/index.md'
        - Custom Recipes: 'resources/server/recipes/custom.md'
        - Ingredients: 'resources/server/recipes/ingredients.md'
        - Non-Datapack Recipes:  'resources/server/recipes/incode.md'
      - Global Loot Modifiers: 'resources/server/glm.md'
      - Tags: 'resources/server/tags.md'
      - Conditionally-Loaded Data: 'resources/server/conditional.md'
  - Data Generation:
    - Introduction: 'datagen/index.md'
    - Client Assets:
      - Model Providers: 'datagen/client/modelproviders.md'
      - Language Providers: 'datagen/client/localization.md'
      - Sound Providers: 'datagen/client/sounds.md'
    - Server Data:
      - Recipe Providers: 'datagen/server/recipes.md'
      - Tag Providers: 'datagen/server/tags.md'
      - Global Loot Modifier Providers: 'datagen/server/glm.md'
  - Miscellaneous Features:
    - Configuration: 'misc/config.md'
    - Game Tests: 'misc/gametest.md'
    - Forge Update Checker: 'misc/updatechecker.md'
    - Debug Profiler: 'misc/debugprofiler.md'
  - Advanced Topics:
    - Access Transformers: 'advanced/accesstransformers.md'
  - Contributing to Forge:
    - Introduction: 'forgedev/index.md'
    - Pull Request Guidelines: 'forgedev/prguidelines.md'
  - Legacy Versions:
    - Introduction: 'legacy/index.md'
    - Porting to This Version: 'legacy/porting.md'

# Do not edit in PRs below here
site_name: Forge Documentation
site_url: https://mcforge.readthedocs.io/en/1.18.x/

markdown_extensions:
  - admonition
  - smarty
  - sane_lists
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - toc:
      permalink: ' '

theme:
  name: readthedocs
  custom_dir: forge_theme

extra:
  current_version: 1.18.x
  versions:
    1.16.x: 1.16.x
    1.18.x: 1.18.x

extra_css:
  - css/version_warning_fix.css
